version: '3.7'
# TODO: mount node_modules
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    # restart: always
    networks:
      - app-network
    logging:
      driver: none

  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 8000:8000
    volumes:
      - ./packages/backend:/usr/src/app/packages/backend
      - /usr/src/app/packages/backend/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    depends_on:
      - mongo
    command: yarn backend:dev

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 3000:3000
    volumes:
      - ./packages/frontend:/usr/src/app/packages/frontend
      - /usr/src/app/packages/frontend/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: yarn frontend:start

networks:
  app-network:
    driver: bridge
