version: '3.7'
services:
  backend:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 8000:8000
    volumes:
      - ./packages:/usr/src/app/packages
      - /usr/src/app/backend/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: yarn backend:dev

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
      target: BASE
    ports:
      - 3000:3000
    volumes:
      - ./packages:/usr/src/app/packages
      - /usr/src/app/frontend/node_modules
    networks:
      - app-network
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: yarn frontend:start

networks:
  app-network:
    driver: bridge
